### ISSUE TITLE
GNSS module not connected to either UART nor USB of ARM

### ISSUE THREAD

**Issue by laf0rge** [myriadrf/LimeNET-Micro#3]
As far as I'm reading the schematics (also confirmed by my experiments), the GNSS module seems only connected to the FPGA by default.  As for the UART, I can understand that that to some extent, as the softcore in the FPGA might want to communicate with the GNSS chip to understand whether or not the receiver has a fix, etc.

But for the USB, I'm a bit puzzled.  Both R96 and R97 are marked as "NF" (not fit), and indeed they are not placed on the board.  Why leave it to the user to solder those 0402 resistors if he wants to run software on the host that interacts with the GNSS module?

BTS monitoring software typically also wants to know at the very least the lock status of the receiver.  It also might want to know the geographic position of the device to assist in netwokr planning.  Particularly for small cells or even femtocells the position is not known a-priori like in a macro site where you first are building an antenna tower and should know where it's actually located.

**Comment by vbuitvydas** [comment]
UART of GNSS is connected to FPGA and GNSS_UART_TX line is connected to Raspberry Pi by default. Check   [3.8 Communication interfaces (I2C, UART, SPI)](https://wiki.myriadrf.org/LimeNET-Micro_v2.1_hardware_description#Communication_interfaces_.28I2C.2C_UART.2C_SPI.29). Raspberry Pi can receive status from GNSS through UART. Also in current gateware FPGA can receive fix and location status and store it to internal registers which are also accessible from host (GNSS-> FPGA -> FTDI -> HOST).

So already there is an option for host to access status from GNSS and for this reason R96,R97 are left NF, this gives other option to connect some external USB device to J11 connector.
