### ISSUE TITLE
Is the barrel connector for 5V DC or 12V DC?

### ISSUE THREAD

**Issue by laf0rge** [myriadrf/LimeNET-Micro#4]
The README file at https://github.com/myriadrf/LimeNET-Micro/blob/master/README.md states "12V DC barrel connector" while the board silk-screen of a 2v1 board clearly reads "5V DC" next to the connector.

Please fix accordingly. There might be other places to fix like the wiki, I didn't check that part.

**Comment by laf0rge** [comment]
https://myriadrf.org/projects/integrated/limenet-micro/ also states 12V

**Comment by laf0rge** [comment]
https://wiki.myriadrf.org/LimeNET_Micro states 5V

**Comment by laf0rge** [comment]
https://wiki.myriadrf.org/LimeNET-Micro_v2.1_hardware_description also states 5V

**Comment by vbuitvydas** [comment]
> The README file at https://github.com/myriadrf/LimeNET-Micro/blob/master/README.md states "12V DC barrel connector" while the board silk-screen of a 2v1 board clearly reads "5V DC" next to the connector.
> 
> Please fix accordingly. There might be other places to fix like the wiki, I didn't check that part.

Fixed;



> https://wiki.myriadrf.org/LimeNET_Micro states 5V

Correct statement;



> https://wiki.myriadrf.org/LimeNET-Micro_v2.1_hardware_description also states 5V

Correct statement;
